// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HeadBackupRestoreSpecApplyConfiguration represents a declarative configuration of the HeadBackupRestoreSpec type for use
// with apply.
//
// HeadBackupRestoreSpec defines the backup and restore configuration for the Ray head pod
// using the GKE PodSnapshot feature (podsnapshots.gke.io).
type HeadBackupRestoreSpecApplyConfiguration struct {
	// Enable indicates whether to enable periodic backup for the Ray head pod.
	Enable *bool `json:"enable,omitempty"`
	// BackupInterval specifies the interval for taking periodic snapshots.
	BackupInterval *metav1.Duration `json:"backupInterval,omitempty"`
	// StorageConfigName is the name of the PodSnapshotStorageConfig resource used to store the snapshots.
	StorageConfigName *string `json:"storageConfigName,omitempty"`
	// RestoreFrom specific snapshot name. When specified, the operator will add the
	// `podsnapshot.gke.io/ps-name` annotation to restore the head pod from this snapshot.
	RestoreFrom *string `json:"restoreFrom,omitempty"`
}

// HeadBackupRestoreSpecApplyConfiguration constructs a declarative configuration of the HeadBackupRestoreSpec type for use with
// apply.
func HeadBackupRestoreSpec() *HeadBackupRestoreSpecApplyConfiguration {
	return &HeadBackupRestoreSpecApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *HeadBackupRestoreSpecApplyConfiguration) WithEnable(value bool) *HeadBackupRestoreSpecApplyConfiguration {
	b.Enable = &value
	return b
}

// WithBackupInterval sets the BackupInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupInterval field is set to the value of the last call.
func (b *HeadBackupRestoreSpecApplyConfiguration) WithBackupInterval(value metav1.Duration) *HeadBackupRestoreSpecApplyConfiguration {
	b.BackupInterval = &value
	return b
}

// WithStorageConfigName sets the StorageConfigName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageConfigName field is set to the value of the last call.
func (b *HeadBackupRestoreSpecApplyConfiguration) WithStorageConfigName(value string) *HeadBackupRestoreSpecApplyConfiguration {
	b.StorageConfigName = &value
	return b
}

// WithRestoreFrom sets the RestoreFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestoreFrom field is set to the value of the last call.
func (b *HeadBackupRestoreSpecApplyConfiguration) WithRestoreFrom(value string) *HeadBackupRestoreSpecApplyConfiguration {
	b.RestoreFrom = &value
	return b
}
