# to test local kuberay changes
# make build && ./bin/manager -leader-election-namespace default -metrics-addr :8085

apiVersion: podsnapshot.gke.io/v1alpha1
kind: PodSnapshotStorageConfig
metadata:
  name: ray-snapshot-storage
spec:
  snapshotStorageConfig:
    gcs:
      bucket: sizhang-ray-experimental
      path: ray-snapshots
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-snapshot-test
spec:
  rayVersion: '2.52.0'
  headGroupSpec:
    headBackupRestore:
      enable: true
      backupInterval: 2m
      storageConfigName: ray-snapshot-storage
    rayStartParams:
      node-ip-address: "raycluster-snapshot-test-head-svc.default.svc.cluster.local"
    template:
      spec:
        serviceAccountName: ray-ksa
        runtimeClassName: gvisor
        nodeSelector:
          cloud.google.com/gke-nodepool: ps-node-pool
        tolerations:
        - key: "sandbox.gke.io/runtime"
          operator: "Equal"
          value: "gvisor"
          effect: "NoSchedule"
        containers:
        - name: ray-head
          image: rayproject/ray:2.52.0
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          env:
          - name: RAY_gcs_rpc_server_reconnect_timeout_s
            value: "300"
          - name: RAY_gcs_server_request_timeout_seconds
            value: "300"
          - name: RAY_raylet_rpc_server_reconnect_timeout_max_s
            value: "300"
          - name: RAY_health_check_failure_threshold
            value: "60"
          - name: RAY_health_check_period_ms
            value: "5000"
          - name: RAY_health_check_timeout_ms
            value: "300000"
          - name: RAY_health_check_initial_delay_ms
            value: "30000"
          - name: RAY_py_gcs_connect_timeout_s
            value: "300"
          - name: RAY_node_death_timeout_ms
            value: "300000"
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 20
            exec:
              command:
              - bash
              - -c
              - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget --tries 1 -T 10 -q -O- http://localhost:8265/api/gcs_healthz | grep success
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 20
            exec:
              command:
              - bash
              - -c
              - wget --tries 1 -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget --tries 1 -T 10 -q -O- http://localhost:8265/api/gcs_healthz | grep success
  workerGroupSpecs:
  - replicas: 2
    minReplicas: 2
    maxReplicas: 2
    groupName: workers
    rayStartParams: {}
    template:
      spec:
        serviceAccountName: ray-ksa
        runtimeClassName: gvisor
        nodeSelector:
          cloud.google.com/gke-nodepool: ps-node-pool
        tolerations:
        - key: "sandbox.gke.io/runtime"
          operator: "Equal"
          value: "gvisor"
          effect: "NoSchedule"
        containers:
        - name: ray-worker
          image: rayproject/ray:2.52.0
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
